/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package driver;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hafsa Rashid
 */
public class ViewPendingRequests extends javax.swing.JFrame {
            Employee emp = new Employee();
    public ViewPendingRequests() {
        initComponents();
        showDataInTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pendingRqst = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Pending Requests");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jButton9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        pendingRqst.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pendingRqst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "LoginID", "Contact No", "Department", "Rank", "Item Name", "Quantity", "Company"
            }
        ));
        jScrollPane2.setViewportView(pendingRqst);
        if (pendingRqst.getColumnModel().getColumnCount() > 0) {
            pendingRqst.getColumnModel().getColumn(3).setResizable(false);
            pendingRqst.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Pending Requests");

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton1.setText("Issue Accessories");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(288, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(274, 274, 274)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton9))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jLabel2)
                    .addContainerGap(316, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        ManageEmployees manage = new ManageEmployees();
        manage.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Items item = new Items();
//        int instance = 0;
        for (int i = 0; i < Employee.request.size(); i++) {
        String loginID = Employee.request.get(i).getLoginID();
        String contactNo = Employee.request.get(i).getContactNo();
        String department = Employee.request.get(i).getDepartment();
        String rank = Employee.request.get(i).getRank();
        String itemName = Employee.request.get(i).getItemName();
        String quantity = Employee.request.get(i).getQuantity();
        String company = Employee.request.get(i).getCompany();
        int index1 = item.searchitem(itemName);
        int a = Integer.parseInt(AccManager.itemList.get(index1).getQuantity());
        int b = Integer.parseInt(quantity);
        //JOptionPane.showMessageDialog(null, "Quantity." + "a = " + a + " b = " + b + " itemname " + itemName);

        //int Quantity = AccManager.itemList.get(index1).getQuantity().compareTo(quantity);
        if (a >= b) {
            int c = a - b;
            item = AccManager.itemList.get(index1);
            item.setItemName(itemName);
            item.setQuantity(c + "");
            item.setCompany(company);
            AccManager.itemList.set(index1, item);
            emp.setLoginID(loginID);
            emp.setContactNo(contactNo);
            emp.setDepartment(department);
            emp.setRank(rank);
            emp.setItemName(itemName);
            emp.setQuantity(quantity);
            emp.setCompany(company);
            Employee.request.set(index1, emp);
            JOptionPane.showMessageDialog(null, "Request has been issued.");
            if ((i+1) == Employee.request.size()) {
                JOptionPane.showMessageDialog(null, "NO ISSUE.");
                this.setVisible(false);
            }
            /*issueAcc.setItemName(itemName);
            issueAcc.setQuantity(quantity);
            issueAcc.setCompany(company);
            IssuedAcc.issueAcc.set(index1, issueAcc);
            JOptionPane.showMessageDialog(null, "ISSUE.");*/

        } else {
            //JOptionPane.showMessageDialog(null, "Quantity." + "a = " + a + " b = " + b + " itemname " + itemName);
            JOptionPane.showMessageDialog(null, "Sorry, we are out of stock.");
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPendingRequests.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPendingRequests.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPendingRequests.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPendingRequests.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPendingRequests().setVisible(true);
            }
        });
    }

    public void showDataInTable() {
        tbModel = (DefaultTableModel) pendingRqst.getModel();
        tbModel.setRowCount(0);
        for (int i = 0; i < Employee.request.size(); i++) {
            Object[] obj = new Object[7];
            obj[0] = Employee.request.get(i).getLoginID();
            obj[1] = Employee.request.get(i).getContactNo();
            obj[2] = Employee.request.get(i).getDepartment();
            obj[3] = Employee.request.get(i).getRank();
            obj[4] = Employee.request.get(i).getItemName();
            obj[5] = Employee.request.get(i).getQuantity();
            obj[6] = Employee.request.get(i).getCompany();
            tbModel.addRow(obj);
        }
    }

    DefaultTableModel tbModel;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable pendingRqst;
    // End of variables declaration//GEN-END:variables
}
